# Generated by Django 5.0 on 2023-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_amer'),
    ]

    operations = [
        migrations.AddField(
            model_name='amer',
            name='hi',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
