# Generated by Django 5.0 on 2023-12-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_amer_hi'),
        ('app', '0010_security_note_date'),
    ]

    operations = [
    ]
